import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./_components/Header";
import { Outfit } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

const inter = Outfit({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="mx-4 md:mx-16">
          <Toaster />
            <Header /> {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
